### ISSUE TITLE
New Stationeers version incopability (sbn/lbn)

### ISSUE THREAD

**Issue by jmwierzbicki** [Stationeers-ic/vscode-stationeers-ic10#58]
`sbn` and `lbn` Are not recognized. Also new preprocessing macros does not work. `HASH("some-string")` should be possible to insert as any number argument

![image](https://github.com/Traineratwot/vscode-stationeers-ic10/assets/11833720/9636199d-80e7-4df0-8948-bf6b1b4b442d)
![image](https://github.com/Traineratwot/vscode-stationeers-ic10/assets/11833720/48d0828e-5e0f-4862-ac38-cf40c84b7c59)

**Comment by xavierdemoor** [comment]
`HASH("name")` doesn't accept name with space between words

**Comment by Traineratwot** [comment]
Fixed HASH with space :)
