### ISSUE TITLE
while loop causes invalid error report

### ISSUE THREAD

**Issue by jmwierzbicki** [Stationeers-ic/vscode-stationeers-ic10#59]
Using While loop causes block not closed error.

![image](https://github.com/Traineratwot/vscode-stationeers-ic10/assets/11833720/d69b540d-a7b3-45ad-9165-659866cb4b9e)

**Comment by Traineratwot** [comment]
I am currently working on a completely new version of Ios based on an already existing language. the current syntax will not be supported. I hope I will succeed. Our discord server https://discord.com/invite/KSVjXufkA9
