### ISSUE TITLE
select method not translating var names into registers

### ISSUE THREAD

**Issue by jmwierzbicki** [Stationeers-ic/vscode-stationeers-ic10#60]
as in screenshot, self explainatory

![image](https://github.com/Traineratwot/vscode-stationeers-ic10/assets/11833720/ff9c08b7-e34f-461a-a8a8-0a7993fd908f)

**Comment by Traineratwot** [comment]
I am currently working on a completely new version based on an already existing language. the current syntax will not be supported. I hope I will succeed. Our discord server https://discord.com/invite/KSVjXufkA9
