### ISSUE TITLE
 device channels not working and hex and binary preprocessor not working

### ISSUE THREAD

**Issue by shaddowlinkk** [Stationeers-ic/vscode-stationeers-ic10#63]
**Describe the bug**
 device channels not working and hex and binary preprocessor not working

**To Reproduce**
s db:1 Channel0 r5
define datamask $00000000ffffffff

**Expected behavior**
first line set value of r5 on Channel0 on Device connection 1
second line set datamask to equal 4,294,967,295
**Screenshots**
![problem](https://github.com/Stationeers-ic/vscode-stationeers-ic10/assets/4326154/64b91208-7a4d-48b3-8820-f3eb9a29cbee)

**Additional context**

**Comment by Traineratwot** [comment]
fixed
